# Generated by Django 6.0.4 on 2026-05-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
